// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sign-up-container': string;
  'signUpContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
