// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'loader': string;
  'rotate': string;
  'rotateccw': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
