// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'display-container': string;
  'displayContainer': string;
  'item-container': string;
  'item-name': string;
  'itemContainer': string;
  'itemName': string;
  'magnifying-glass': string;
  'magnifyingGlass': string;
  'search-container': string;
  'searchContainer': string;
  'searchbar': string;
  'to-cart': string;
  'toCart': string;
}
export const cssExports: CssExports;
export default cssExports;
