// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'display-container': string;
  'displayContainer': string;
  'item-container': string;
  'itemContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
