// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cart': string;
  'header': string;
  'user-info': string;
  'userInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
