// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cart-container': string;
  'cartContainer': string;
  'container': string;
  'descrip': string;
  'image': string;
  'image-container': string;
  'imageContainer': string;
  'item-name': string;
  'itemName': string;
  'quant-input': string;
  'quantInput': string;
  'to-cart': string;
  'toCart': string;
}
export const cssExports: CssExports;
export default cssExports;
