// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'image': string;
  'item-name': string;
  'itemName': string;
  'to-cart': string;
  'toCart': string;
}
export const cssExports: CssExports;
export default cssExports;
