// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cart-container': string;
  'cart-item': string;
  'cart-item-info': string;
  'cartContainer': string;
  'cartItem': string;
  'cartItemInfo': string;
  'checkout-button': string;
  'checkout-container': string;
  'checkoutButton': string;
  'checkoutContainer': string;
  'empty': string;
  'item-quantity': string;
  'itemQuantity': string;
  'page-container': string;
  'pageContainer': string;
  'quant-buttons': string;
  'quant-buttons-container': string;
  'quant-container': string;
  'quantButtons': string;
  'quantButtonsContainer': string;
  'quantContainer': string;
  'remove-cart': string;
  'removeCart': string;
}
export const cssExports: CssExports;
export default cssExports;
