// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cart-container': string;
  'cart-item': string;
  'cartContainer': string;
  'cartItem': string;
}
export const cssExports: CssExports;
export default cssExports;
