// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth': string;
  'form': string;
  'input': string;
  'label': string;
  'prompt': string;
  'sign-button': string;
  'sign-up-container': string;
  'signButton': string;
  'signUpContainer': string;
  'submit-button': string;
  'submitButton': string;
  'type': string;
}
export const cssExports: CssExports;
export default cssExports;
